{% set name = "pycashier" %}
{% set version = "2024.1006" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycashier-{{ version }}.tar.gz
  sha256: 4a655998a885b2d66490f0a35852ff5f622b6fe3e07215a998afba040c43b8e3

build:
  number: 0
  noarch: python
  entry_points:
    - pycashier = pycashier.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.13
    - pdm-backend
  run:
    - python >=3.8,<3.13
    - rich >=12.0.0
    - click-rich-help >=22.1.0
    - click >=8.1.0
    - tomlkit >=0.10.1
    - polars >=0.20.4

test:
  imports:
    - pycashier
  commands:
    - pip check
    - pycashier --help
  requires:
    - pip

about:
  home: https://github.com/brocklab/pycashier/
  summary: cash in on DNA barcode tags
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
