{% set name = "pycashier" %}
{% set version = "23.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycashier-{{ version }}.tar.gz
  sha256: 7041659ac6887beb7e7d1dee20b818277320492360db3698afb1c84845e32708

build:
  number: 0
  noarch: python
  entry_points:
    - pycashier = pycashier.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - pdm-pep517 >=0.3.0
  run:
    - python >=3.8,<3.11
    - rich >=12.0.0
    - click-rich-help >=22.1.0
    - click >=8.1.0
    - tomlkit >=0.10.1

test:
  imports:
    - pycashier
  commands:
    - pip check
    - pycashier --help
  requires:
    - pip

about:
  home: https://github.com/brocklab/pycashier/
  summary: cash in on DNA barcode tags
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
