{% set name = "pycashier" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycashier-{{ version }}.tar.gz
  sha256: 525ee2baa3958bb004752e5a44335d7dbcabe00ee1d2435b187dde9f4bc34319

build:
  number: 0
  noarch: python
  entry_points:
    - pycashier = pycashier.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - poetry
  run:
    - python >=3.6,<3.10
    - rich >=12.0.0
    - rich-click >=1.2.1, <2.0.0
    - ruamel.yaml >=0.17.21

test:
  imports:
    - pycashier
  commands:
    - pip check
    - pycashier --help
  requires:
    - pip

about:
  home: https://github.com/brocklab/pycashier/
  summary: cash in on DNA barcode tags
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
