{% set name = "pycashier" %}
{% set version = "22.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycashier-{{ version }}.tar.gz
  sha256: 955a3be5dda9da8fd3487736cab83f2e660b35bc4f6ddc294d1672beab0d91c0

build:
  number: 0
  noarch: python
  entry_points:
    - pycashier = pycashier.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - pdm-pep517 >=0.3.0
  run:
    - python >=3.6,<3.10
    - rich >=12.0.0
    - click-rich-help >=22.1.0
    - click >=8.1.0
    - tomlkit >=0.10.1

test:
  imports:
    - pycashier
  commands:
    - pip check
    - pycashier --help
  requires:
    - pip

about:
  home: https://github.com/brocklab/pycashier/
  summary: cash in on DNA barcode tags
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
